apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yml
- backend-service.yml
- redis-service.yml
- redis-stateful-set.yml
- ui-deployment.yml
- ui-service.yml
